### ISSUE TITLE
Update for Bukkit 1.13 release

### ISSUE THREAD

**Issue by timbru31** [timbru31/UnlimitedLava#2]
There are currently occurrences of  `setTypeIdAndData` for setting the desired lava block state and raw byte value comparisons, these will be **deprecated/removed** in Bukkit 1.13. A new API will be created, that has to be used.

**Comment by ardentcrest** [comment]
has this be released for 1.13+ yet

**Comment by timbru31** [comment]
No not yet. The last time the I've checked this Spigot/CraftBukkit seemed to have issues with the events for water/lava flow - I have to re-test if this issue still exists.

**Comment by timbru31** [comment]
Blocking issue: https://hub.spigotmc.org/jira/browse/SPIGOT-3854?focusedCommentId=31888&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-31888

**Comment by timbru31** [comment]
Done via https://github.com/timbru31/UnlimitedLava/commit/d5c801e636a8d5a7d4e38a3ee5a6078b487cf4ad
